codecov:
  disable_default_path_fixes: true
fixes:
  - "/home/runner/work/LodgeSubscriptionBundle/LodgeSubscriptionBundle/plugins/LodgeSubscriptionBundle/::"

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 