name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PLUGIN_DIR: plugins/LodgeSubscriptionBundle

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.0']
        db-types: ['mysql']
        mautic-versions: ['6.0']
        include:
          - db-types: mysql
            database-url: mysql://root:root@127.0.0.1:3306/mautic

    services:
      database:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mautic
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ env.PLUGIN_DIR }}

    - name: Checkout mautic
      uses: actions/checkout@v2
      with:
        repository: mautic/mautic
        path: .
        ref: ${{ matrix.mautic-versions }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
        coverage: pcov

    - name: Setup database
      env:
        DB_PORT: ${{ job.services.database.ports[3306] }}
      run: |
        echo "DB_PORT=$DB_PORT" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ matrix.database-url }}:$DB_PORT/mautic?serverVersion=5.7" >> $GITHUB_ENV

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Code Style check
      run: bin/php-cs-fixer fix ${{ env.PLUGIN_DIR }} --config=.php-cs-fixer.php -v --dry-run --show-progress=dots --diff

    - name: PHPSTAN
      run: composer phpstan -- ${{ env.PLUGIN_DIR }}

    - name: Rector
      run: composer rector -- --dry-run --no-progress-bar ${{ env.PLUGIN_DIR }}

    - name: Twig Lint
      run: bin/console lint:twig ${{ env.PLUGIN_DIR }}

    - name: Run PHPUNIT tests
      env:
        DB_PORT: ${{ job.services.database.ports[3306] }}
      run: XDEBUG_MODE=coverage APP_DEBUG=0 php -dpcov.enabled=1 -dpcov.directory=. -dpcov.exclude="~tests|themes|vendor~" bin/phpunit -d memory_limit=1G --bootstrap vendor/autoload.php --configuration ${{ env.PLUGIN_DIR }}/phpunit.xml --coverage-clover=${{ env.PLUGIN_DIR }}/coverage.xml --coverage-text

    - name: Coverage report
      run: cat ${{ env.PLUGIN_DIR }}/coverage.xml

    - name: Upload coverage report
      if: ${{ matrix.php-versions == '8.0' && matrix.db-types == 'mysql' && matrix.mautic-versions == '6.0' }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        working-directory: ${{ env.PLUGIN_DIR }}
        verbose: true

    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mautic-logs
        path: var/logs/ 